spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://10.24.20.117:3306/igo_basedata?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://10.24.20.116:8761/eureka/
